BUD-07 Paid storage
hzrd149/blossom pull request #29
Opened 2024-09-10 09:03 UTC by quentintaranpino

### BUD-07 Paid upload and download

This pull request introduces `BUD-07`, a new specification outlining how servers can require and handle payments for blob storage. It defines the use of `402 Payment Required` responses, with payment details provided via `X-{payment_method}` headers adhering to method-specific standards like **Cashu (NIP-18)** and **Lightning (BOLT-11)**.

The specification is **designed to be extensible** for future payment methods and includes guidance on client-server interactions.

Readable version [here](https://github.com/hzrd149/blossom/blob/8e12280410443029cbae882450d5714fef930414/buds/07.md)

2024-09-12 07:56 UTC, quentintaranpino commented on buds/07.md
> +For backward compatibility, the server `SHOULD` display a QR code, JSON file, or other useful information instead of the blob in the response body. When the payment is completed, the server `MUST` re
I agree with you that the line about how the server handles serving a blob when payment isn't complete doesn't seem too useful, as this behavior can vary widely depending on the server's implementation. The server could choose to serve the blob for a day, a week, or require periodic payments—the possibilities are indeed endless, so listing them here does seem unnecessary.

However, I do find the backward compatibility section quite useful. One potential approach for showing a paid blob to clients that haven't yet adapted to this BUD, informing the client that the full content is available but requires payment. This way, older clients still receive a meaningful response, even if they don't support the new payment-based logic, while updated clients can fully leverage the payment mechanism.

2024-09-16 07:23 UTC, quentintaranpino commented on buds/07.md
> +For backward compatibility, the server `SHOULD` display a QR code, JSON file, or other useful information instead of the blob in the response body. When the payment is completed, the server `MUST` re
I'm fine with that

2024-11-01 10:03 UTC, quentintaranpino commented
L402 has been discarded in favor of a simpler approach that maintains the overall intent while adding compatibility with any L2, and potentially even other payment methods.

2024-11-18 11:33 UTC, quentintaranpino commented
New version for the PR. This new version replaces the generic X-Payment header with dedicated headers for each supported payment method (e.g., X-Cashu, X-Lightning). This change improves clarity, scalability, and compatibility with future payment systems.

2024-11-20 11:15 UTC, quentintaranpino commented
- Clarified the usage of `X-{payment_method}` headers to include payment details per specification of each method.
- Adjusted schema to indicate encoding aligns with the corresponding method's spec (e.g., NUT-18 for Cashu, BOLT-11 for Lightning).
- Improved examples for both `X-Cashu` and `X-Lightning` headers with real-world use cases.
- Enhanced client implementation details, specifying that payment proof aligns with the selected method's spec.
- Added extensibility guidelines for future payment methods, emphasizing publicly available specifications.
- Updated error handling to include refreshed payment details on failure.

2024-11-20 11:35 UTC, quentintaranpino commented
Added recurring payments section with support for Cashu (NIP-61) and Lightning (NIP-57), requiring an 'x' tag for blob hash reference.

2024-11-20 20:14 UTC, quentintaranpino commented on buds/07.md
> +The client MUST provide the payment proof in the request headers using the same `X-{payment_method}` header that was chosen. The payment proof MUST aling with the payment method specification:
Something like this?

**Special Note on HEAD Requests**

The HEAD endpoints are only used to retrieve blob or server information. They MUST NOT be retried with payment proof. Instead, clients should complete the payment and proceed with the `PUT` or `GET` request.

2024-11-20 20:19 UTC, quentintaranpino commented on buds/07.md
> +### Recurring Payments
I always end up thinking about a GET /info endpoint where general server characteristics could be indicated. But of course, this would be another BUD. We could leave this section with just a note stating that recurring payments are not yet implemented, thoughts?

2024-11-20 20:21 UTC, quentintaranpino commented on buds/07.md
> +If the client fails to provide the payment proof (expired invoice, invalid token, etc.) the server MUST respond with **402 Payment Required** status code and include the relevant `X-{payment_method}`
Something like this?

### Error handling

If the client fails to provide the payment proof (expired invoice, invalid token, etc.) the server MUST respond with **400 Bad request** status code and include a `X-Reason` header with a human-readable message. The client SHOULD inform the user about the error and provide a way to retry the request.

2024-12-03 12:01 UTC, quentintaranpino commented on buds/07.md
> +If the client fails to provide the payment proof (expired invoice, invalid token, etc.) the server MUST respond with **400 Bad request** status code and include a `X-Reason` header with a human-reada
@hzrd149, what do you think about this?

2024-12-03 12:03 UTC, quentintaranpino commented on buds/07.md
> +### Recurring Payments
Removed this section.

2024-12-15 08:23 UTC, quentintaranpino commented on buds/07.md
> +If the client fails to provide the payment proof (expired invoice, invalid token, etc.) the server MUST respond with **400 Bad request** status code and include a `X-Reason` header with a human-reada
If it’s okay with everyone, I’ll leave the status as 400 for now.

2025-02-02 17:04 UTC, v0l commented
Would it not be better to have a simple `POST /payment` and a way to check quota like `GET /account`?

Returning `402` status on upload makes sense when quota is exceeded but automatically returning an invoice seems wrong.

2025-02-02 17:06 UTC, v0l commented
Im looking to implement payments in `route96` and i think a "standard" approach would be better, should i make a PR for my idea of payments?

2025-02-02 17:23 UTC, quentintaranpino commented
> Would it not be better to have a simple `POST /payment` and a way to check quota like `GET /account`?
> 
> Returning `402` status on upload makes sense when quota is exceeded but automatically returning an invoice seems wrong.

I see what you mean, but I don’t think it’s incompatible. This BUD is just about what happens when you try to access a paid resource, it lays out the expected behavior when payment is required.

In my server (which  this BUD is up and running 🤓), the client does a HEAD /upload, gets the cost of the upload (which could be 0 if they have balance), and then decides whether to pay or not. These kinds of decisions are up to the server admin, so I wouldn’t go into that in this BUD. Keeping it simple is best! 😊

But if you’re thinking of submitting another BUD for managing user accounts, I’ve got some ideas for GET /account, it could return more useful data beyond just the pubkey balance.

As for the POST you mentioned, maybe it could be a more general PUT/account endpoint, where users could manage their account settings on the server, and why not, also add funds. What do you think?

2025-02-02 17:30 UTC, quentintaranpino commented
@v0l you can try it here:

https://playground.nostrcheck.me/

2025-02-08 20:00 UTC, hzrd149 commented
> Im looking to implement payments in `route96` and i think a "standard" approach would be better, should i make a PR for my idea of payments?

I would encourage you to use this BUD for payments, it only covers 402 payment requests per API call and not an account based system but as @quentintaranpino mentioned its implemented in nostrcheck and a new server by Leito
https://njump.me/nevent1qvzqqqqqqypzqmajvcqjcvqgxql9ftj4zs95d9t7n9uqnpqpmk357nvjrgn4h79mqyghwumn8ghj7mn0wd68ytnhd9hx2tcpz4mhxue69uhhyetvv9ujuerpd46hxtnfduhsqgqqqxj9uk777zexucqg003wrr6cdhsukjc94hdhkhukdhmsrg6wqvpslfw0

The only reason I have not merged this BUD yet is because I've been lazy and have neglected to make one last change for the `X-Cashu` header

2025-02-15 22:10 UTC, hzrd149 commented on buds/07.md
> +When using the X-Cashu header, the server MUST adhere to the [NUT-18](https://github.com/cashubtc/nuts/blob/main/18.md) standard.
```suggestion 
When using cache for requesting payment for an endpoint, the server MUST respond with a `X-Cashu` header containing a base64 encoded JSON object (payment request)

The payment request should contain an `amount`, `mints`, `unit`, and `pubkey` fields

 - `amount` The amount of ecash being requested
 - `mints` An array of mints that this server uses
 - `unit` The cashu `unit` from the `mints`
 - `pubkey` (optional) a 33 byte pubkey to lock the tokens too. see [NUT-11](https://github.com/cashubtc/nuts/blob/main/11.md)

For example:
\`\`\`json
{
  "amount": 21,
  "unit": "sats",
  "mints": ["https://mint.minibits.cash/Bitcoin"],
  "pubkey": "02a82ec539a2bbd51039c480e8836316036ccb461b9a2e62b49b418c2897851b98"
}
\`\`\`

Would be encoded into

\`\`\`http	
HTTP/1.1 402 Payment Required
X-Cashu: eyJhbW91bnQiOiAyMSwidW5pdCI6ICJzYXRzIiwibWludHMiOiBbImh0dHBzOi8vbWludC5taW5pYml0cy5jYXNoL0JpdGNvaW4iXSwicHVia2V5IjogIjAyYTgyZWM1MzlhMmJiZDUxMDM5YzQ4MGU4ODM2MzE2MDM2Y2NiNDYxYjlhMmU2MmI0OWI0MThjMjg5Nzg1MWI5OCJ9
\`\`\`

```

2025-02-15 22:15 UTC, hzrd149 commented on buds/07.md
> +When using the X-Cashu header, the server MUST adhere to the [NUT-18](https://github.com/cashubtc/nuts/blob/main/18.md) standard.
Finally starting this discussion, I think the `X-Cashu` header from the server should be a base64 encoded JSON object instead of a NIP-18 payment request

The reason is because NIP-18 requires a transport method (http post, or nostr) and has no concept of paying the request using the same method that the request was delivered in

Also the format and encoding benefits of NIP-18 are geared towards showing the payment request to the user as a QRCode, but the primary use case of the `X-Cashu` header is clients and machines automatically responding with a payment in-band

2025-04-19 15:19 UTC, hzrd149 commented on buds/07.md
> +When using the X-Cashu header, the server MUST adhere to the [NUT-18](https://github.com/cashubtc/nuts/blob/main/18.md) standard.
Closing because https://github.com/cashubtc/nuts/pull/239 defines how http 402 should be handled with x-cashu

2025-04-19 15:20 UTC, hzrd149 requested changes

2025-04-19 15:20 UTC, hzrd149 commented on buds/07.md
> +When using the X-Cashu header, the server MUST adhere to the [NUT-18](https://github.com/cashubtc/nuts/blob/main/18.md) standard.
```suggestion
When using the X-Cashu header, the server MUST adhere to the [NUT-23](https://github.com/cashubtc/nuts/pull/239) standard.
```

2025-04-19 15:20 UTC, hzrd149 commented on buds/07.md
> +When using the X-Cashu header, the server MUST adhere to the [NUT-18](https://github.com/cashubtc/nuts/blob/main/18.md) standard.
Update to use NUT-23 HTTP Payment required

2025-07-30 17:58 UTC, merged

2025-07-30 18:00 UTC, hzrd149 commented
@quentintaranpino I updated this to point to [NUT-24](https://github.com/cashubtc/nuts/blob/main/24.md) and merged :+1: 

I should have merged it months ago and I'm sorry I ignored it so long

2025-08-31 09:46 UTC, quentintaranpino commented
@hzrd149 Thanks for merging BUD-07!! 🥳🥳🥳🥳